turtle game (reach the beach)
hackclub/sprig pull request #1198
Opened 2023-10-25 05:39 UTC by Eevi0n

# Your checklist for this pull request

## Author name 

**Daniel Dunavetsky**

## About your game

**15 levels of a baby turtle trying to reach the ocean and not getting eaten**

**press WASD to move and if you want to restart press i press l to start and reach the ocean complete the level(first level isplayed twice to understand controls) **

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

2023-10-25 16:28 UTC, Eevi0n commented
My friend went to maker faire and told me about it since she knew I like making games

2023-10-25 18:19 UTC, LucasHT22 requested changes
Wow Maker Faire! Did you win the game? I didn't haha

2023-10-25 18:21 UTC, Eevi0n commented
which game? I didnt go to maker faire or am I not understanding

2023-10-25 18:24 UTC, Eevi0n commented
sorry for the dumb question but this is my first pull request so I don't know how it works but how do i see the requested changes that were asked for?

2023-10-25 18:29 UTC, LucasHT22 commented
> which game? I didnt go to maker faire or am I not understanding

Oh sorry, I meant your sprig game :)

2023-10-25 18:30 UTC, Eevi0n commented
O ya i beat it once but i feel like it is a bit harder then I intended :)

2023-10-25 18:34 UTC, LucasHT22 commented on games/turtle game (reach the beach).js
> +
like this

2023-10-25 18:40 UTC, LucasHT22 commented
Please check this: The name of the file/game contains only alphanumeric characters, -s, or _s. :)

2023-10-25 19:07 UTC, Eevi0n commented
I think I fixed it

2023-10-25 21:00 UTC, LucasHT22 commented
Could you rename the image too? Thanks:)

2023-10-25 22:27 UTC, Eevi0n commented
sorry im having trobule changing the name of a png do i need to like delete it and then reupload it or is there a way to do it on github

2023-10-25 23:30 UTC, LucasHT22 commented
Don't apologize!! You need to delete and reupload:)

2023-10-26 00:30 UTC, Eevi0n commented
I cant upload the new png it say
"File uploads require push access to this repository."

2023-10-26 01:18 UTC, LucasHT22 commented
Try on your fork, if you can't make it either, I can merge and then you make other PR with the updated version or you send to me and I add

2023-10-26 01:23 UTC, Eevi0n commented
Ya I can not if I try to edit the PNG the button is grayed out

2023-10-26 02:34 UTC, LucasHT22 approved these changes
Probably some bug, please make other PR with the update:) Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

2023-10-26 02:35 UTC, merged