new pull request templates
hackclub/sprig pull request #1236
Opened 2023-11-12 02:22 UTC by LucasHT22

needs polish but here is

2023-11-13 15:28 UTC, grymmy commented on .github/PULL_REQUEST_TEMPLATE/games.md
> +about: Submiting your game!
nit: typo

2023-11-13 15:28 UTC, grymmy approved these changes

2023-11-16 18:45 UTC, grymmy approved these changes
lgtm

2023-11-16 18:47 UTC, grymmy commented
@JosiasAurel plz look at these and give feedback if desired - are we asking all that we should for all of these?

2023-11-16 18:53 UTC, JosiasAurel commented
I think it's worth asking if the PR author has tested their changes to make sure it doesn't break anything else in the project.

2023-11-16 18:54 UTC, JosiasAurel requested changes
we should ask if the author has tested their changes and asserted that it doesn't break anything else

2023-11-17 23:53 UTC, LucasHT22 commented
Sorry for the delay! Done.

2023-11-20 13:13 UTC, JosiasAurel approved these changes
lgtm

2023-11-20 22:47 UTC, LucasHT22 commented
Was reading about it, and looks like this won't work, also the possibly solution just complicate more. Closing this for now, sorry to make you review for nothing.

Ref: https://stackoverflow.com/questions/73771068/multiple-templates-for-pull-requests-on-github
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request

2023-11-20 22:47 UTC, closed without merging