getting started page
hackclub/sprig pull request #1237
Opened 2023-11-12 03:54 UTC by LucasHT22

2023-11-13 15:29 UTC, grymmy commented on src/pages/sprikipedia/getting-started/acknowledgements.astro
> +// spriki19
what is this?

2023-11-13 16:06 UTC, LucasHT22 commented on src/pages/sprikipedia/getting-started/acknowledgements.astro
> +// spriki19
per our discussion, removed

2023-11-16 18:49 UTC, grymmy commented
> _ No description provided. _

please add a good description to this PR that describes what it does

2023-11-16 18:50 UTC, grymmy requested changes
see comment

2023-11-17 10:00 UTC, LucasHT22 commented
Done

2023-11-17 16:08 UTC, grymmy approved these changes

2023-11-17 23:42 UTC, merged