Sprikipedia
hackclub/sprig pull request #1275
Opened 2023-12-01 16:39 UTC by itsimpeccable

I did moderate changes to the sprikipedia, adding more team members to team page, adding a sprikipedia redirection URL to the homepage, and I made Philosophy and Acknowledgements page to the one page named "About Sprig".

2023-12-01 16:55 UTC, LucasHT22 requested changes
Hey! Really thank you for this PR! Make some comments, please don't get me wrong, I'm just being careful with this:)

2023-12-01 16:55 UTC, LucasHT22 commented on src/components/navbar-main.tsx
> +				<li><a href='/sprikipedia'>Sprikipedia</a></li>
Sprikipedia isn't ship'ed yet! So we won't add it to the main navbar for now

2023-12-01 16:55 UTC, LucasHT22 commented on src/pages/sprikipedia/getting-started/about-sprig.astro
> -</Categories>
Disagree with the rename, getting-started folder follow README.md, and in README.md is https://github.com/hackclub/sprig#acknowledgements

2023-12-01 16:55 UTC, LucasHT22 commented on src/pages/sprikipedia/getting-started/philosophy.astro
> -<p>People learn best when they make things that they care about, which they can then share with others. This type of learning philosophy is called constructionism, and Sprig is a type of microworld.
Why delete it? 👀

2023-12-01 16:55 UTC, LucasHT22 commented on src/pages/sprikipedia/team/index.astro
>      <p>{data["team.categories.about"]}</p>
I appreciate your changes but I'm already preparing for spriki29 with reference to https://github.com/hackclub/sprig/blob/main/RESPONSIBILITIES.md :)

2023-12-01 16:55 UTC, LucasHT22 commented on games/LabyrinthRedux.js
> +/*
Please make another PR for your game:)

2024-03-14 15:01 UTC, Sheepy3 commented
Hi, is this PR still active?

2024-06-13 12:47 UTC, closed without merging

2024-06-13 12:47 UTC, grymmy commented
I am closing this PR only due to its old age, and thus it seems unlikely it will land.  @LucasHT22 feel free, absolutely, to reopen this PR if you desire to push it towards landing to mainline.

2024-06-13 18:50 UTC, itsimpeccable commented
I was not active about sprikipedia and yeah graham, you should've closed
this already.

On Thu, Jun 13, 2024 at 3:47 PM graham ***@***.***> wrote:

> I am closing this PR only due to its old age, and thus it seems unlikely
> it will land. @LucasHT22 <https://github.com/LucasHT22> feel free,
> absolutely, to reopen this PR if you desire to push it towards landing to
> mainline.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/1275#issuecomment-2165559257>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMITSM6EASHZGPOFX7H7REDZHGIFVAVCNFSM6AAAAABADDGXLGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRVGU2TSMRVG4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>