Implemented Automate Plagiarism / Copy Detection
hackclub/sprig pull request #1285
Opened 2023-12-06 20:14 UTC by DevIos01

As we talked about in #1177 I have implemented the automation workflow to check through all existing games in sprig and compare them with the new PR file to check if it matches or not to improve our PR process.

Here is an example:
![image](https://github.com/hackclub/sprig/assets/34939959/0a654e36-95f9-4c80-b383-0f68f3e2d577)

![image](https://github.com/hackclub/sprig/assets/34939959/e53ac6a7-ea9c-44e3-be75-70eed6ed958d)

2023-12-07 05:43 UTC, DevIos01 commented
yo @SamDev-7 , totally, idk why i did not come up with that , will make few changes to this and some other thoughts after the PR

2023-12-07 14:22 UTC, grymmy commented on .github/scripts/plagiarismCheck.js
> +const calculateSimilarity = (code1, code2) => {
We could use something straight-forward like https://www.npmjs.com/package/fast-diff

2023-12-17 12:45 UTC, LucasHT22 requested changes
I trust you but why prettier?

2023-12-17 12:49 UTC, DevIos01 commented
> I trust you but why prettier?

Good Catch, this was used for the last few commit, but making a new commit with it being removed as we don't need it anymore :)

2023-12-17 13:00 UTC, LucasHT22 approved these changes
Looks everything ok to me, lmk when you ok with merge

2023-12-17 16:07 UTC, DevIos01 commented
Alight ready to rumble, open the door ;) 🕺 
![giphy](https://github.com/hackclub/sprig/assets/34939959/280806a4-6acb-4194-9f43-697eebb8007d)

2023-12-17 17:22 UTC, merged