possible new above the fold site :)
hackclub/sprig pull request #1370
Opened 2024-01-07 07:04 UTC by bellesea

2024-01-10 16:41 UTC, grymmy commented
@leomcelroy I don't think this originated from an issue - please look at this and provide feedback, and remove yourself from assignees when done plz

2024-01-10 16:49 UTC, JosiasAurel requested changes
besides the formatting changes, lgtm and tested 👍🏾

2024-01-10 16:49 UTC, JosiasAurel commented on src/pages/index.astro
please could you update the PR to not include formatting changes? It makes it challenging to read the diff

2024-01-15 03:46 UTC, leomcelroy commented
I like the effort to constantly improve the site but overall I'm not a huge fan of these changes.

The main improvements I see are:

- The background makes some more sense. The original background is essentially just a dark image we liked that is pixelated.
- There is an explicit cue that the model is interactive.

The things I'm less keen on are:

- The large Sprig title is mostly obscured by the model which looks busy and haphazard.

<img width="795" alt="Screenshot 2024-01-14 at 10 42 45 PM" src="https://github.com/hackclub/sprig/assets/27078897/5bcab1c9-72f4-44c2-82d0-6bef8a68fe01">

- The explicit interactive callout blends in with the background. (refer to previous image)
- As you scroll the model obscures the text on the page.

<img width="958" alt="Screenshot 2024-01-14 at 10 43 14 PM" src="https://github.com/hackclub/sprig/assets/27078897/2aea07fe-1a5d-4f58-a232-387f899f621c">

- The new copy comes across has highly transactional, I read more emphasis on "free" rather than "craft" as it was before.
- The scroll animation reaches it's final state when the model is at the top of the page rather than the middle.

<img width="1398" alt="Screenshot 2024-01-14 at 10 41 56 PM" src="https://github.com/hackclub/sprig/assets/27078897/0b1e9703-e938-46d6-a5cd-fb649b01e4d8">

<img width="1394" alt="Screenshot 2024-01-14 at 10 42 26 PM" src="https://github.com/hackclub/sprig/assets/27078897/6188e71b-3476-454f-af6c-fe43255d70f1">

- All the green colors start to clash.

Considering all of this if we feel compelled to update this portion of the page I would maybe go ahead with finding a new background and adding some cue that you can interact with the 3D model.

2024-01-15 04:09 UTC, bellesea commented
hey @leomcelroy thanks sm for the feedback! will try to implement! it looks like some of it is a responsive issue, which device did you check this on?

2024-04-03 15:48 UTC, Sheepy3 commented
Hi, is this PR abandoned?

2024-04-30 13:39 UTC, grymmy commented
@bellesea do we plan on landing this?

2024-04-30 14:32 UTC, bellesea commented
> @bellesea do we plan on landing this?

@grymmy i don't think so — wasn't able to get it reliably working on low end computers. I think we can close this for now? Thank you!

2024-06-06 20:51 UTC, grymmy commented
@JosiasAurel I know I talked w/ you today about resurrecting this but actually @snoglobe is a good fit and will own getting this to production.

2024-06-23 01:04 UTC, snoglobe commented
done in https://github.com/hackclub/sprig/pull/1802

2024-06-23 01:04 UTC, closed without merging