add infinite loop detection
hackclub/sprig pull request #1413
Opened 2024-01-29 11:51 UTC by JosiasAurel

the sprig editor will throw an error if
1. there are more than 2000 iterations in a loop AND
2. the loop takes > 1.5s to complete

addresses #1091

2024-01-29 13:57 UTC, grymmy requested changes
Please answer a few questions for me:

1. Is this performant? (will it slow down the execution of games?)  How do you know?
2. What is the UX when an infinite loop is detected?
3. Is this more likely to flag as inf loop when your computer is under load? 
4. Where do we intend on documenting this watchdog behavior such that people are not surprised when encountering this?

Separately (I won't demand this), it would be nice to have a few unit tests here proving it works.

2024-01-29 13:58 UTC, grymmy commented on src/lib/transform-detect-infinite-loop.ts
> +	const MAX_ITERATIONS = 2000;
Suggest moving these to environment variables (or to another constants definition that's higher-level in the project).

2024-01-29 14:00 UTC, grymmy reviewed
Can you also ensure that `debugger` statements continue to work w/ this?

2024-02-01 12:45 UTC, JosiasAurel commented
> Please answer a few questions for me:
> 
> 1. Is this performant? (will it slow down the execution of games?)  How do you know?
> 2. What is the UX when an infinite loop is detected?
> 3. Is this more likely to flag as inf loop when your computer is under load?
> 4. Where do we intend on documenting this watchdog behavior such that people are not surprised when encountering this?
> 
> Separately (I won't demand this), it would be nice to have a few unit tests here proving it works.

1. I have tested these changes with a few games in the gallery and there was no noticeable slow down. 
2. This will show up as an error in the editor (see original comment)
3. I'm not sure
4. This will be added directly in the toolkit page in the editor 

<img width="369" alt="image" src="https://github.com/hackclub/sprig/assets/47951376/9567c84e-88ee-4fdb-8541-88d5c98f3147">

2024-02-01 13:01 UTC, JosiasAurel commented
> Can you also ensure that `debugger` statements continue to work w/ this?

debugger statements still work

2024-02-01 14:41 UTC, Goldenpig12345 commented
Oh, My Goodness! it's so nice to see you again! How's Anne doing? I
have seen her since she was three!
My doctor has recently said you haven't eaten enough turnips lately. Do you
know if this is true? I really miss you and we need to catch up soon. do
you still have my number? oh, it's okay if you don't I'll just send it to
you. my number is (802)-658-5667. oh ad I heard that your mother was
arrested could you tell me what happened? something about an adult diaper
chase at Walmart? anyway please get back to me soon and maybe we could do
lunch. Love You Lots.

On Thu, Feb 1, 2024 at 8:01 AM Josias Aurel ***@***.***>
wrote:

> Can you also ensure that debugger statements continue to work w/ this?
>
> debugger statements still work
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/1413#issuecomment-1921277583>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDLIQWXO6ANGNFNKFE6LRP3YROG3RAVCNFSM6AAAAABCPJIL5SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRRGI3TONJYGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-02-01 14:49 UTC, grymmy commented on docs/docs.md
> +### Infinite loop detection
Suggest cutting this.  Users will experience it intuitively and this probably shouldn't be above the "Getting Help" section.

2024-02-01 14:57 UTC, grymmy approved these changes

2024-02-01 16:22 UTC, merged