Better Gallery Tagging UI & QoL fixes
hackclub/sprig pull request #1438
Opened 2024-02-15 19:34 UTC by GalaxyGamingBoy

Resolves #1420

2024-02-15 20:00 UTC, JosiasAurel requested changes
left some comments. overall looks good to me though

2024-02-15 22:25 UTC, GalaxyGamingBoy commented on src/pages/gallery/gallery.tsx
> +							onClick={() => window.open(`/gallery/${game.filename}`, '_blank')}
React's `event.persist()` only works on functions, as such to be able to click the tag I had to remove the href functionality

2024-02-15 22:26 UTC, GalaxyGamingBoy commented on src/pages/gallery/gallery.tsx
> +		}
Sure, the only problem is that I will have to copy paste it which generally isn't a good practice, that's why I opted for a global-ish way

2024-02-16 15:09 UTC, GalaxyGamingBoy commented on src/pages/gallery/gallery.tsx
> +		games.forEach(game => {
A reduce with a map as an accumulator seems iffy style wise imo but I'll see

2024-02-22 21:46 UTC, GalaxyGamingBoy commented on src/pages/gallery/gallery.tsx
> +		}
@JosiasAurel Should I leave it be, it seems more efficient that copy-pasting it a bunch of times over the 2-3 on selects

2024-02-28 11:34 UTC, GalaxyGamingBoy commented
@grymmy @JosiasAurel Am I free to merge?

2024-03-01 11:52 UTC, merged