Introduce Auto-Format to Sprig Editor  #1399
hackclub/sprig pull request #1475
Opened 2024-03-05 13:06 UTC by DevIos01

### **Introduction**
This pull request introduces an Auto-Format feature to the editor, aimed at improving code readability and consistency. The motivation behind this feature is to provide an easy-to-access tool for users, especially beginners and those participating in hackathons, to automatically format their code. This addresses the common issue of inconsistent code styling, such as indentation and spacing, making the codebase cleaner and easier to read.

### **Changes Made**
Added **stripWhitespaceAndUpdate** function to include js-beautify options.
Added a menu item "Prettify code" in the dropdown, linked to the updated function.

### **Before & After**

**Before: Code that's a bit all over the place.**
![image](https://github.com/hackclub/sprig/assets/34939959/b13ec3da-5c49-4b33-948d-d0a591a2acf3)

**After: Nicely formatted code that's easy on the eyes.**
![image](https://github.com/hackclub/sprig/assets/34939959/2376abd0-f8b5-4033-beaa-3c4851fa633d)

2024-03-05 13:11 UTC, JosiasAurel requested changes

2024-03-05 13:11 UTC, JosiasAurel commented on src/components/navbar-editor.tsx
> +        e4x: true,
please add a comment specifying what this option does

2024-03-05 13:11 UTC, JosiasAurel commented on src/components/navbar-editor.tsx
> +        brace_style: "end-expand",
also this one

2024-03-05 13:11 UTC, JosiasAurel commented on src/components/navbar-editor.tsx
> +        jslint_happy: false,
also this one

2024-03-05 13:57 UTC, JosiasAurel approved these changes

2024-03-08 18:15 UTC, leomcelroy commented
Look good to me.

2024-03-08 18:15 UTC, merged

2024-03-08 18:22 UTC, leomcelroy commented
I reverted this after testing some more. 

Here is the snippet I often use for formatting.

```js
function formatCode(code) {
  try {
    const options = {
      indent_size: 2,
      "brace_style": "collapse,preserve-inline",
    }
    return js_beautify(code, options)
  } catch (error) {
    console.log(error)
    return code // return the original code if there's an error
  }
}
```