Implement Playable Community Game On HomePage
hackclub/sprig pull request #1623
Opened 2024-04-27 15:49 UTC by DevIos01

as requested on #1568, I have implemented so that it takes the random game from "New Tag" and renders the game

2024-05-01 00:09 UTC, grymmy commented
@DevIos01 please revisit the linked-to issue and get product mgmt approval (retroactively) for this work

2024-05-01 00:09 UTC, grymmy requested changes
see prev. comment

2024-06-07 12:55 UTC, JosiasAurel requested changes

2024-06-07 12:55 UTC, JosiasAurel commented on src/pages/index.astro
> +	const response = await fetch("http://localhost:3000/api/gallery?new");
this won't work in production will it?

2024-06-07 12:55 UTC, JosiasAurel commented on src/pages/index.astro
> +		<div id='gamesource-data' data-gamesource={gamesource} style={{ displa: "none", visibility: "hidden"}}></div>
should be `display` and not `displa`

2024-06-07 12:55 UTC, JosiasAurel commented on src/pages/index.astro
> +					pressedScreen: false,
what do these changes do?

2024-07-01 17:11 UTC, grymmy commented
@DevIos01 Do you intend on moving forward with this?  If not, please close it.

2024-07-01 17:12 UTC, grymmy commented
actually nevermind... I don't feel a strong need for this feature period.  Closing it myself, DM me if u really want to advocate for this

2024-07-01 17:12 UTC, closed without merging