Document the tags used on the games
hackclub/sprig pull request #1637
Opened 2024-05-01 18:48 UTC by GalaxyGamingBoy

2024-05-02 10:48 UTC, JosiasAurel requested changes
there are a few corrections to be made. 
also please avoid formatting the code in the future it makes it hard to see the code diff

2024-05-02 10:48 UTC, JosiasAurel commented on src/pages/get.astro
> +							<a href="https://hackclub.com/slack/" target="_blank">#sprig</a> channel on the <a href="https://hackclub.com/slack/" target="_blank">slack</a>
replace the link for `#sprig` with `https://hackclub.slack.com/archives/C02UN35M7LG`

2024-05-02 10:48 UTC, JosiasAurel commented on src/pages/get.astro
> +							any assistance feel free to sent a message on the
should be `send` and not `sent`

2024-05-02 10:48 UTC, JosiasAurel commented on src/pages/get.astro
> +							> <strong>tag selection dropbox</strong> but you can always add new ones. The metadata tag @tags
~dropbox~ dropdown

2024-05-02 10:54 UTC, GalaxyGamingBoy commented on src/pages/get.astro
> +							> <strong>tag selection dropbox</strong> but you can always add new ones. The metadata tag @tags
my bad

2024-05-02 17:42 UTC, leomcelroy commented
What sort of feedback are you looking for on this review? I can describe what it's supposed to do but I think reviewing the code itself for correctness is outside my purview.

2024-05-08 10:24 UTC, JosiasAurel commented
> What sort of feedback are you looking for on this review? I can describe what it's supposed to do but I think reviewing the code itself for correctness is outside my purview.

I am looking for feedback on the submission steps - [see updated steps here](https://sprig-1qpblsv1q-gamer.vercel.app/get)

2024-05-13 17:55 UTC, grymmy approved these changes
Seems fine to me, if verbose (could be a smaller singular section).

2024-05-20 17:38 UTC, leomcelroy commented
Only have title and author in the the default file. The additional information should be referenced in the submission doc not the default example.

2024-05-22 18:54 UTC, GalaxyGamingBoy commented
@leomcelroy Removed the other tags in the template

2024-06-10 21:07 UTC, GalaxyGamingBoy commented
Before:
![image](https://github.com/hackclub/sprig/assets/53054461/6a810d04-220f-4e64-a45e-b37b4daac881)

After:
![image](https://github.com/hackclub/sprig/assets/53054461/273d6c0a-3d69-4b5c-805d-9fc6a91896f5)

2024-06-10 23:12 UTC, grymmy requested changes
Plz make more concise and I believe this section is best left to end

2024-06-10 23:14 UTC, GalaxyGamingBoy commented
> Plz make more concise and I believe this section is best left to end

Okay, I can make it more concise. But the position should ideally be first, since you kind of need it before committing the game/pr

2024-06-21 15:24 UTC, GalaxyGamingBoy commented
![image](https://github.com/hackclub/sprig/assets/53054461/4c9ecfaa-eef4-43ef-917b-9c00fffe93aa)

2024-06-25 13:56 UTC, JosiasAurel approved these changes

2024-08-01 17:19 UTC, closed without merging