Seperate firebase from accounts.ts to firebase.ts
hackclub/sprig pull request #1638
Opened 2024-05-01 19:12 UTC by GalaxyGamingBoy

closes #1596

2024-05-01 19:14 UTC, GalaxyGamingBoy commented
Plagiarism Checker failing because of multiple js files being inputted

2024-05-27 08:52 UTC, JosiasAurel requested changes
please have you tested and made sure the application works properly across?

2024-05-27 08:52 UTC, JosiasAurel commented on games/Countdown_Golf.js
it would be ideal if you don't include unrelated changes in a PR

2024-05-27 09:16 UTC, GalaxyGamingBoy commented on games/Countdown_Golf.js
The change of the golf game was due to having my main branch as the origin. The change was also warranted because without it the build failed

2024-06-21 15:22 UTC, closed without merging

2024-07-09 19:04 UTC, GalaxyGamingBoy commented
I am fixing the commit, missed some places and got minor conflicts