Add files via upload
hackclub/sprig pull request #1698
Opened 2024-05-22 15:09 UTC by Ebit22

# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-05-22 16:09 UTC, grymmy requested changes
Neat game!

Please change the file path of your game to the games/ directory per the submission instructions.

2024-05-22 16:11 UTC, grymmy commented
I would also note that I found this game somewhat hard to play given the input keybindings (wsad didn't work as I'd expect)

2024-05-24 10:32 UTC, Ebit22 commented
I can't upload the file in the [/games directory]

2024-05-24 10:34 UTC, Ebit22 commented on Roodkapje.js
> +onInput("a", () => {
```suggestion
onInput("w", () => {
```

2024-05-24 10:34 UTC, Ebit22 commented on Roodkapje.js
> +onInput("w", () => {
```suggestion
onInput("a", () => {
```

2024-05-30 15:11 UTC, grymmy commented
Neat game!  Congratulations, if you're a teen, you can order a Sprig by filling out this form here: https://sprig-order.hackclub.dev/

2024-05-30 15:11 UTC, grymmy approved these changes

2024-05-30 15:11 UTC, merged