Created UI for creating, editing and viewing rooms
hackclub/sprig pull request #1800
Opened 2024-06-20 17:40 UTC by claynicholson

2024-06-20 18:19 UTC, Cosmin-Mare approved these changes
lgtm! doesn't influence anything outisde the beta workflow. But there's no close button, and there should be a view password button, so u can continue working on that and I'm going to start implementing the actual functionality into the UI

2024-06-20 19:01 UTC, JosiasAurel requested changes

2024-06-20 21:25 UTC, claynicholson commented on src/components/design-system/input.tsx
> +	readonly?: boolean
The box is meant to meant to display the link to get copied. I wanted to use the same style from the other input boxes so  it just acts as a display box.

2024-06-20 21:26 UTC, claynicholson commented on src/components/popups-etc/share-room.tsx
> +						const textToCopy = "www.example.com";
Yes it does, I believe Cosmin is adding the link generation to it so I am just using it as a placeholder.

2024-06-20 21:28 UTC, claynicholson commented on src/components/popups-etc/share-room.tsx
> +					value="www.example.com"
alright, will do in the future.

2024-06-20 21:28 UTC, claynicholson commented on src/components/popups-etc/share-room.tsx
> +       						 console.error('Failed to copy text: ', err);
Alright Ill add that

2024-06-20 21:29 UTC, claynicholson commented on src/components/popups-etc/share-room.tsx
> +					<form onSubmit={async (event) => {
Cosmin is implementing this I believe.

2024-06-21 15:20 UTC, Cosmin-Mare commented
@JosiasAurel I'll add the stuff u mentioned, I just need this code on the main branch so I can work on it. It won't influence users anyways for now, that's what I need confirmation for

2024-06-24 14:25 UTC, grymmy commented on src/components/popups-etc/share-room.tsx
> +					value="www.example.com"
The future is now, plz make this change.

2024-06-24 14:26 UTC, grymmy commented on src/components/popups-etc/share-room.tsx
> +					<form onSubmit={async (event) => {
Seeing as this doesn't effect prod, it is fine for this to be a placeholder.

2024-06-25 20:19 UTC, Cosmin-Mare approved these changes
lgtm! @JosiasAurel do we have your blessing?:))

2024-06-27 12:12 UTC, JosiasAurel approved these changes
blessed!

2024-06-27 15:35 UTC, merged