menu opens on hover
hackclub/sprig pull request #1801
Opened 2024-06-20 18:59 UTC by Patcybermind

someone made an issue asking for the popup menu to open on hover so here it is

2024-06-21 15:11 UTC, grymmy commented on .env.example
This probably shouldn't be deleted...?

2024-06-21 15:18 UTC, grymmy commented on src/components/navbar-editor.tsx
Please avoid mass indentation changes that are not associated with your actual change - it makes it very hard to review.

2024-06-21 15:19 UTC, grymmy requested changes
Please remove all unnecessary formatting from this PR - it makes it hard to review properly.

2024-06-21 15:21 UTC, Patcybermind commented
Ok ill make the changes sorry

2024-06-21 17:59 UTC, Patcybermind commented
i reviewed it with the diftool and it should now be okay

2024-07-01 17:15 UTC, grymmy commented
Two things - I still see what seem to be a lot of indentation changes that were made unnecessarily - also, there is a merge conflict that needs to be dealt w/...

2024-09-17 07:53 UTC, JosiasAurel commented
@Patcybermind do you plan on continuing work on this PR?

2024-09-20 19:08 UTC, Patcybermind commented
yeah.. i cant do it
sorry

2025-01-02 19:31 UTC, grymmy commented
Closing this PR due to inactivity.

2025-01-02 19:31 UTC, closed without merging