Create Slimer.js
hackclub/sprig pull request #1897
Opened 2024-07-04 23:54 UTC by 29cmb

# Your checklist for this pull request

## Author name

**Author: DevCmb**

## About your game

**What is your game about?**

Use keys, blocks, and other items to reach the end!

**How do you play your game?**

WASD to move

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

2024-07-05 15:22 UTC, grymmy requested changes
Hey - this is a really good start, but can you please add a new mechanic or two to bring it up to the quality level we expect for Sprig device grants?  Doesn't need to be anything major, but a little twist would get you there...

2024-07-05 18:39 UTC, 29cmb commented
Well that sucks, ADDING POWERUPS!!!

2024-07-05 20:58 UTC, 29cmb commented
I added multiple-player gimmick, powerup to move 2 spaces, and a few more levels

2024-07-11 18:38 UTC, grymmy commented
Looking now.

2024-07-11 18:44 UTC, grymmy commented
Congratulations!  If you're a teenager, and you haven't already received a Sprig device, feel free to fill in [this form](https://sprig-order.hackclub.dev/) to receive one of your very own!  Also feel free to join Hack Club's Slack and share your creation in the #sprig channel!

2024-07-11 18:44 UTC, merged