Name modal instead of auto generation
hackclub/sprig pull request #1944
Opened 2024-07-11 19:26 UTC by ShubhamPatilsd

dev update, instead of auto generating a name, prompt the user to create one. solves #1744 

<img width="1356" alt="image" src="https://github.com/hackclub/sprig/assets/55328098/3566804f-adc5-4e51-a93c-fb92df2084d1">

2024-07-11 19:30 UTC, grymmy commented on src/pages/~/new.ts
> -import type { APIRoute } from 'astro'
My suggestion is to leave the existing route and others may have integrated w/ it.  Add yours in an additive/non-conflicting manner.

2024-07-11 19:31 UTC, grymmy requested changes
plz resolve my one comment re: the deleted route, and also can u see why the gh action warnings are showing up inline here?

2024-07-11 20:14 UTC, ShubhamPatilsd commented
updated

2024-07-12 16:27 UTC, grymmy approved these changes

2024-07-12 16:30 UTC, merged