Feat: autocomplete
hackclub/sprig pull request #2144
Opened 2024-08-12 21:54 UTC by youknowedo

Added autocomplete to the web editor. Uses the default CodeMirror JavaScript autocomplete with some custom completions for Sprig-specific functions. It also includes tooltips that show the documentation for that function imported from the docs.

2024-08-12 22:01 UTC, youknowedo commented
Currently reads the docs, puts it inside an HTMLElements `innerHTML`, and then reads the `innerHTML` again. This is because the regex seemed to have problems with the Unicode characters the "compiled content" would give. Feel free to change it since there must be a more efficient way to do this, I just haven't figured it out yet.

2024-09-17 07:50 UTC, JosiasAurel requested changes
I love the way the completion looks. However it might break if the documentation doc changes. 
Now that the Sprig engine is in the sprig repository, it might be better to read from the [exposed engine API](https://github.com/hackclub/sprig/blob/12e832146da281845df051e17543130c4bbd5689/engine/src/base/index.ts#L283)

2024-09-17 07:50 UTC, JosiasAurel commented on src/lib/codemirror/init.ts
> +import widgets from "./widgets";
It's generally good to avoid formatting changes in a PR as it makes it hard to read the diff. Can you undo the formatting here?

2024-09-17 07:50 UTC, JosiasAurel commented on src/lib/codemirror/init.ts
> +								index = count;
Please undo the formatting changes. It makes it hard to read what has actually changed.

2025-02-18 15:17 UTC, grymmy commented
Closing this due to inactivity.

2025-02-18 15:17 UTC, closed without merging