Feat: Stack Changes
hackclub/sprig pull request #2288
Opened 2024-09-03 23:37 UTC by GalaxyGamingBoy

Implements a custom linker script for the memory mappings.  
Currently we place the changes are:
+ Core0 (SCRATCH_X) stack after Core1 (SCRATCH_Y) 
+ Core0 stack size to be alloc be 6MB, Core1 stack size to be alloc 2MB

2024-09-26 18:54 UTC, recursiveforte requested changes

2024-09-26 18:54 UTC, recursiveforte commented on firmware/spade/src/rpi/CMakeLists.txt
> +  JERRY_SYSTEM_ALLOCATOR=1
why are you switching to the system allocator here? (instead of the default jerryscript BSS block)

2024-09-26 18:56 UTC, recursiveforte commented
pls make sure to test that audio works w/ this pr- if we increase stack size, it might eat into the heap space used for the audio buffer

2024-10-31 00:29 UTC, GalaxyGamingBoy commented
> pls make sure to test that audio works w/ this pr- if we increase stack size, it might eat into the heap space used for the audio buffer

Tested a few games today with audio and it appears to work as expected

2025-02-18 15:17 UTC, closed without merging