Sprig DVD Screensaver - Yash Vardhan Niranjan
hackclub/sprig pull request #2404
Opened 2024-10-02 06:35 UTC by Yash00241

# Your checklist for this pull request

## Author name

**Author: Yash Vardhan Niranjan**

## About your game

**What is your game about?**
It is the iconic DVD screensaver for Sprig ;D

**How do you play your game?**
No Need for Controls just start the game 💃 

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-10-03 14:33 UTC, grymmy requested changes
If you're interested in receiving a Sprig device grant, unfortunately this does not meet the bar as it does not have at least 1 minute of gameplay.  I am fine w/ merging this w/o providing a grant, but if that's not desirable then please add to this some sort of interactive game mechanic that meets the bar.

2024-10-03 15:32 UTC, Yash00241 commented
Hey @grymmy as it is a screensaver for sprig, I would prefer it to be this way only as it looks much more beautiful right now also, for the grant I would try to make a game.
I would request you to merge my art piece in the gallery 😄

2024-10-14 09:36 UTC, Yash00241 commented
@grymmy

2024-12-05 18:29 UTC, grymmy commented
Ah - sorry for missing this months back.  Yes, I will merge this even though it does not qualify for the grant.

2024-12-06 10:26 UTC, Yash00241 commented
Thanks :)

On Thu 5 Dec, 2024, 11:59 PM graham, ***@***.***> wrote:

> Ah - sorry for missing this months back. Yes, I will merge this even
> though it does not qualify for the grant.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/2404#issuecomment-2521125713>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT5MJS2PML6RQ6IR3S7MN7T2ECLRZAVCNFSM6AAAAABPHAOTUOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRRGEZDKNZRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-02 19:37 UTC, merged