Add files via upload
hackclub/sprig pull request #2422
Opened 2024-10-05 19:43 UTC by alicia392

# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-10-07 23:35 UTC, alx-alexpark requested changes
Hey there! Congrats on your game! Could you provide your name, and some information about your game, including what your game is about and how to play it? (The information in the template). Thanks!

2024-10-07 23:35 UTC, alx-alexpark commented on games/A Monster Maze.js
> +@tags: []
Optional, but do you want to add some tags related to your game?

2024-10-09 22:25 UTC, alicia392 commented
My name is Alicia and the game is like a maze which gets harder and there are more monsters and even fake coins and fake walls to make each level harder. Also I didn't plagiarize but it's probably because the games are all mazes and the code isn't too complicated.

2024-10-10 15:19 UTC, alx-alexpark commented
Sorry, but could you differentiate the game from the games you remixed by adding new mechanics with a focus on writing new original code?

2025-01-03 14:08 UTC, closed without merging

2025-01-03 14:08 UTC, grymmy commented
I am closing this due to inactivity.