Add files via upload
hackclub/sprig pull request #2563
Opened 2024-11-07 00:20 UTC by klaus-E2S

# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-11-07 01:43 UTC, alx-alexpark commented
Hii, Could you fill in the information in the pull request template?

2024-11-08 21:30 UTC, klaus-E2S commented
Alright, I've filled out the information.

On Wed, Nov 6, 2024 at 8:43 PM Alex Park ***@***.***> wrote:

> Hii, Could you fill in the information in the pull request template?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/2563#issuecomment-2461145770>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMXDRPLH5HRRLHV2HP6AQ2TZ7LAUNAVCNFSM6AAAAABRKAXYMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRRGE2DKNZXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-13 00:38 UTC, alx-alexpark requested changes
Hey!!

Your game is really cool, but we require 1 minute of novel gameplay, and your game unfortunately doesn't meet that requirement. You can add more levels, or game mechanics to increase your game's playtime. If you need help, feel free to ask in #sprig!

2024-11-15 20:09 UTC, klaus-E2S commented
Yeah, I had a feeling that would be the case. I'll work on that.

On Tue, Nov 12, 2024 at 7:38 PM Alex Park ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey!!
>
> Your game is really cool, but we require 1 minute of novel gameplay, and
> your game unfortunately doesn't meet that requirement. You can add more
> levels, or game mechanics to increase your game's playtime. If you need
> help, feel free to ask in #sprig!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/2563#pullrequestreview-2431245408>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMXDRPMQALXMRNMPSSN43JL2AKNQHAVCNFSM6AAAAABRKAXYMKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZRGI2DKNBQHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-28 02:36 UTC, klaus-E2S commented
damn can't upload .js files so sad, anyway this should work, here's the updated version

[toilet cleaning simulator totally awesome (2).zip](https://github.com/user-attachments/files/17942038/toilet.cleaning.simulator.totally.awesome.2.zip)

2025-01-03 16:03 UTC, grymmy commented
I updated the code here with the code within the zip file up provided here.  Unfortunately, this game still doesn't meet the minimum requirements for a Sprig device grant.  Could you add a novel mechanic or two to the game?

2025-02-18 18:33 UTC, grymmy commented
Closing this PR due to inactivity

2025-02-18 18:33 UTC, closed without merging

2025-02-21 01:42 UTC, klaus-E2S commented
Dang, I didn't get this notification for whatever reason. Just out of curiosity, what exactly are some examples of novel mechanics?