Add files via upload
hackclub/sprig pull request #2629
Opened 2024-11-23 01:11 UTC by Bluelightning26

# Your checklist for this pull request

## Author name

**Blu**

## About your game
Fight your way to the opposing player's endzone while they push back, the twine will get shorter with more pushes when your opponent is in their own endzone. This is a two player game, designed to be simple while taking advantage of the Sprig’s layout.

**How do you play your game?**

Player 1: Press D to go forward
Player 2: Press J to go forward

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-11-26 03:35 UTC, gusruben requested changes
Nice game, I like the concept! It doesn't quite reach a full minute of novel gameplay (though it's obviously very player-dependant), but could you maybe add another feature or two, like multiple rounds, to extend the playtime? If you do I'll be happy to approve it!

2024-11-26 21:12 UTC, Bluelightning26 commented
Hello! Thank you for the feedback! Instead of adding rounds, I felt like the game needed more strategy. To add more of this to the game I allowed the players to freeze their opponents controls for one second by pressing “w” or “i” respectively . Each player only gets five times to freeze their opponents controls so they have to use it at the right time. I believe this greatly improves the game and extends the playtime at the same time, while also being more fun. Thank you for pushing me!

2024-11-26 23:14 UTC, gusruben commented
Thanks for your submission, I'll accept it :)

If you're a teen, you can get your Sprig here! [sprig-order.hackclub.dev](https://sprig-order.hackclub.dev/)

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/) ;)

2024-12-09 03:24 UTC, gusruben approved these changes

2024-12-09 03:27 UTC, merged