[Sprig App] the untitled game ultra
hackclub/sprig pull request #2667
Opened 2024-11-29 21:15 UTC by Rayaan4819

### Author name
Author: Rayaan4819

### About your game

**What is your game about?**
its a game that is purly text based (for now), it is a choice game, where as you solve riddles you unlock new paths which therefore unlock new endings (7 endingd for now)

**How do you play your game?**
you will get 3 options, choose any three options to get diffrent paths

2024-12-04 06:35 UTC, gusruben requested changes
Thanks for your submission! It seems there's a bug on line 123 though that stops the program from running, would you mind checking that out?

Also, from reading the code it looks like this might use browser functions like `prompt` and `alert`. I like the thinking outside the box, but to accept the game it would need to be built in the Sprig engine! If you modified/rewrote the game to use Sprig I'd be happy to approve it!

2024-12-04 08:48 UTC, Rayaan4819 commented
Thanks for the help, Yea it did have browser elements and its kind of just
an idea i got over the weekend and will definitely go more in detail once
my exams are over, Thanks fp=or your time

On Wed, Dec 4, 2024 at 10:36 AM Gus Ruben ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for your submission! It seems there's a bug on line 123 though that
> stops the program from running, would you mind checking that out?
>
> Also, from reading the code it looks like this might use browser functions
> like prompt and alert. I like the thinking outside the box, but to accept
> the game it would need to be built in the Sprig engine! If you
> modified/rewrote the game to use Sprig I'd be happy to approve it!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/2667#pullrequestreview-2477412652>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDGO7GUMLEYENRNCHQO5RG32D2PGHAVCNFSM6AAAAABSXYJ2ESVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZXGQYTENRVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-03 20:55 UTC, grymmy commented
@Rayaan4819 do you plan on moving forward with this PR?

2025-02-18 23:23 UTC, grymmy commented
Closing this as it has unresolved commentary, and is also very old.

2025-02-18 23:23 UTC, closed without merging