Add files via upload
hackclub/sprig pull request #2673
Opened 2024-11-30 04:29 UTC by AL-Sayed1

# Your checklist for this pull request

## Author name

**Author:** Sayed Hashim

## About your game

**What is your game about?**

**Catch The Banana** is a fast-paced, retro-style arcade game where you race against time to catch falling bananas before they hit the lava! Move the bawl left or right to grab as many bananas as possible to score points. Watch out for special blue bananas, they increase the time by 5 seconds! If a banana falls into the lava, you lose points, and letting too many slip could end your game.

**How do you play your game?**
Press "d" to move right, "a" to move left and "j" to restart.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

2024-12-04 06:43 UTC, gusruben requested changes
Thanks for your submission! I like the game a lot, but it doesn't meet the requirement of 1 minute of playtime-- could you maybe extend the timer (or implement anything else) to reach 1 minute of playtime?

If you do I'll be happy to approve your game!

2024-12-05 05:38 UTC, AL-Sayed1 reviewed
I updated the timer to be 60 seconds

2024-12-06 16:09 UTC, gusruben commented
Thanks, nice game :)

If you're a teen, you can get your Sprig here! [sprig-order.hackclub.dev](https://sprig-order.hackclub.dev/)

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/) ;)

2024-12-09 03:24 UTC, gusruben approved these changes

2024-12-09 03:27 UTC, merged