Beyblade Battle
hackclub/sprig pull request #2677
Opened 2024-12-01 05:47 UTC by ShwetaShaw76

## Author name

**Author:**

Shweta Shaw

## About your game

**What is your game about?**

A 2-player Beyblade battle game, the one who goes out of the stadium first loses.

**How do you play your game?**

Hit "run" to execute the code and
start the game (you can also press shift+enter).

Controls for Player 1:
  w -> UP
  a -> LEFT
  s -> DOWN
  d -> RIGHT

Controls for Player 2:
  i -> UP
  j -> LEFT
  k -> DOWN
  l -> RIGHT

On Game Over, i to Restart

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

2024-12-04 07:32 UTC, gusruben requested changes
Nice game! Thanks for your submission, it brings back fond memories :)
Unfortunately I'm worried that it won't hit the required 1 minute of novel playtime for many players, do you think you could find a way to extend the playtime (maybe by adding a rounds system)? If you did that I would be happy to approve your game!

2024-12-06 18:44 UTC, ShwetaShaw76 commented
hey @gusruben, i've  updated the game with more levels, can you check it once

2024-12-06 19:19 UTC, gusruben commented
Thanks, that looks good to me!

If you're a teen, you can get your Sprig here! [sprig-order.hackclub.dev](https://sprig-order.hackclub.dev/)

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/) ;)

2024-12-09 03:23 UTC, gusruben approved these changes

2024-12-09 03:26 UTC, merged