[Sprig App] SkyFall
hackclub/sprig pull request #2697
Opened 2024-12-10 21:29 UTC by Meowkewok

### Author name
Author: Meowkewok

### About your game

**What is your game about?**
Dodge Meteorites and survive as long as possible!

**How do you play your game?**
A/D- Movement
J- Reset
L- Lose

2024-12-20 17:37 UTC, gusruben requested changes
Thanks for your submission! I like your game a lot, but after a few rounds of meteors there's often a round that's impossible, and while that would normally be fine I worry it doesn't hit the required 1 minute of playtime. Do you think you could add more features or change the meteor spawning mechanics so the game lasts longer? If you did, I would be happy to approve your game!

2024-12-20 19:53 UTC, Meowkewok commented
> Thanks for your submission! I like your game a lot, but after a few rounds of meteors there's often a round that's impossible, and while that would normally be fine I worry it doesn't hit the required 1 minute of playtime. Do you think you could add more features or change the meteor spawning mechanics so the game lasts longer? If you did, I would be happy to approve your game!

I think that I fixed it, but I do not know how to update the PR. should I make a new one?

2025-01-03 18:11 UTC, grymmy commented
@Meowkewok you can navigate to "File changed" tab here in the github UI, then select 'Edit file' to modify your game.

2025-02-18 23:32 UTC, grymmy commented
Closing this as it has unresolved commentary, and is also very old.

2025-02-18 23:33 UTC, closed without merging