Inf_maze
hackclub/sprig pull request #2708
Opened 2024-12-13 20:34 UTC by no-one449

# Your checklist for this pull request

## Author name

**Author: Pinyuan zheng**

## About your game

**DO THE MAZE  and hope you go though the right way**

**Use WASD and go though finish lines as the end  and make it to the real ending**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2024-12-20 18:52 UTC, gusruben requested changes
Thanks for your submission! It seems clear that there was a lot of effort put into this game, but I can't seem to figure out how to get past this level! If this is just a mistake on my part you should let me know, though you could consider adding clearer instructions if it's a misunderstanding and not a puzzle. If this is a bug, though, I'd be happy to approve your game after it's fixed!

![image](https://github.com/user-attachments/assets/b6abd95a-1f93-4977-aa05-d0e52db66f33)

2024-12-21 18:25 UTC, no-one449 commented
That how it works I made some of the maps so that you are just stuck and you have to restart  cause it is fun to restart and also there are map maps and there is only one winning map but if you go the wrong way for the map then you get to make more fun to get back to the map for the win

2024-12-28 12:01 UTC, no-one449 commented
It a part of the game

On Fri, Dec 20, 2024 at 1:52 PM Gus Ruben ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for your submission! It seems clear that there was a lot of effort
> put into this game, but I can't seem to figure out how to get past this
> level! If this is just a mistake on my part you should let me know, though
> you could consider adding clearer instructions if it's a misunderstanding
> and not a puzzle. If this is a bug, though, I'd be happy to approve your
> game after it's fixed!
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/b6abd95a-1f93-4977-aa05-d0e52db66f33>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/2708#pullrequestreview-2518144318>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BNWA6TWW7NDJCWRDXRWZFJD2GRROPAVCNFSM6AAAAABTSWFB2SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJYGE2DIMZRHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-03 18:17 UTC, grymmy requested changes
This game's content is too bitmap-heavy, and doesn't exhibit enough actual code / logic, which is the primary thing we want to see uniquely authored by Sprig game authors.  Please add a mechanic or two that requires some code logic, and then I'll merge this & award a Sprig device.

2025-01-10 20:27 UTC, no-one449 commented
I added new enemies and updated the game files on the original pull request so it's less bitmap heavy

2025-02-19 00:45 UTC, grymmy commented
Sorry, this continues to be too bitmap-heavy, and thus I am closing this PR due to not responding to commentary.

2025-02-19 00:45 UTC, closed without merging