[Sprig App] heartgame
hackclub/sprig pull request #2720
Opened 2024-12-17 14:06 UTC by Tech-with-anmol

### Author name
Author: Tech-with-anmol

### About your game

**What is your game about?**
this is  a game where you have to save your heart from enemies, a fast paced and endless game

**How do you play your game?**
use key A and D for left and right movement and save yourself from enemies.

2024-12-20 20:11 UTC, gusruben requested changes
Thanks for your submission! I like the game, but unfortunately I'm getting an error after dying: `TypeError: can't access property "x", p is undefined`. If you fix this, I'd be happy to approve your game!

2024-12-21 05:37 UTC, Tech-with-anmol commented
hi, just update the code, look like i by mistake removed the line "if (!p) return;" which was causing the issue. now it's all good.

2024-12-21 05:53 UTC, Tech-with-anmol commented
Hi, I am really sorry for making changes two time, but I wanted to update the memory management for better performance and better error handling

2025-01-03 21:00 UTC, grymmy requested changes
I think this game needs a bit more additional complexity to quality for a sprig grant.

2025-02-19 00:48 UTC, grymmy commented
Closing this as it has unresolved commentary, and is also very old.

2025-02-19 00:48 UTC, closed without merging