Breadmaze
hackclub/sprig pull request #443
Opened 2022-10-12 19:33 UTC by hamsterkoo

2022-10-12 19:46 UTC, LucasHT22 requested changes
Thanks for PR! Good game! Could you add more levels?
And maybe add a mechanism to make it different from maze and skoban

2022-10-12 19:56 UTC, LucasHT22 commented
If you need help, you can call me! :)

2022-10-13 21:00 UTC, LucasHT22 commented
After adding the levels, I find it interesting to add a timer to make it more competitive:
`//timer time
var total = 10;
     var timer = setInterval(function(){
     total--;
     clearText();
     addText(""+total, { y: 1 , color: [255,0,0] });
       if(total <= 0){
         //for the player to not be able to complete the game after the timer ends
         clearTile(getFirst(player).x,getFirst(player).y);
         clearInterval(timer);
         addText("Game over!")
     }
     },1000);`

2022-10-19 23:31 UTC, hamsterkoo commented
Hi,

Thanks for the feedback. 2 levels and a timer feature has been added.



On Thu, Oct 13, 2022 at 5:00 PM Lucas ***@***.***> wrote:

> After adding the levels, I find it interesting to add a timer to make it
> more competitive:
> //timer time var total = 10; var timer = setInterval(function(){ total--;
> clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <=
> 0){ //for the player to not be able to complete the game after the timer
> ends clearTile(getFirst(player).x,getFirst(player).y);
> clearInterval(timer); addText("Game over!") } },1000);
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/443#issuecomment-1278173265>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3RKFZVUPVM7VZ236OPOKMDWDB2ADANCNFSM6AAAAAARDS6KBQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-20 00:16 UTC, LucasHT22 reviewed
great changes! could increase the timer? oh, thanks for the credits :)

2022-10-20 17:25 UTC, LucasHT22 reviewed
Great changes! music is good :)

2022-10-20 17:25 UTC, LucasHT22 commented on games/BreadMaze.js
> +  //timer - code borrowerd from flurffy
add ``var tempototal = `` and a time to not be able to count to -1

2022-10-20 17:56 UTC, LucasHT22 approved these changes
Congrats :) continue making games! you can get your sprig here! https://sprig-order.hackclub.dev/

2022-10-20 17:57 UTC, merged

2022-10-20 18:41 UTC, hamsterkoo commented
Thanks for all the help!