Criminal
hackclub/sprig pull request #576
Opened 2022-11-20 03:51 UTC by KarenMaza

# Your checklist for this pull request

## About your game

What is your game about? 
Pushing a box.

How to play your game?
 Press WASD to move and push the jail cell on the yellow blob person.
## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

2022-11-20 04:21 UTC, SamDev-7 requested changes
Thanks for the PR! I loved the art! Just some fixes with the comments and it'll be ready to go!

2022-11-20 04:21 UTC, SamDev-7 commented on games/Criminal.js
> +Instructions:
```suggestion
/*
Instructions
```
Uh oh! There seems to be some issues with the comments, make sure they are properly commented.
Let us know if you need any help!

2022-11-20 04:21 UTC, SamDev-7 commented on games/Criminal.js
> +/*
```suggestion
```

2022-11-20 04:25 UTC, LucasHT22 commented
good sprites! my suggestion is to add a background:)

2022-11-24 20:13 UTC, SamDev-7 commented
@KarenMaza You're soo close to getting your Sprig, don't give up!

2022-12-05 18:25 UTC, KarenMaza commented
I'm not sure. I just used it because I made the box a jail cell and the other sprite is kind of hiding from the player. So the sprite is like a criminal running from the detective?

2022-12-05 22:37 UTC, LucasHT22 commented
oh, good idea!

2022-12-05 22:38 UTC, LucasHT22 commented
my suggestion is to add a background:)

2023-01-04 15:14 UTC, SamDev-7 approved these changes

2023-01-19 13:12 UTC, leomcelroy commented
It's been a little while so I'm going to close this PR for now. 

Feel free to reopen if you want to continue working on your game!

2023-01-19 13:12 UTC, closed without merging