Choose your color game
hackclub/sprig pull request #691
Opened 2022-12-31 17:21 UTC by Mani-kanta-0539

# Your checklist for this pull request
yes
## About your game
You have to enter into the color tunnel which you have like.
What is your game about? 
It just funny choosing a color game.You have enter into color tunnel.
How to play your game?
Press WASD to move, J to restart and K to toggle trails. Enter into tunnel with color and alphabets.

## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

2022-12-31 22:03 UTC, LucasHT22 commented
Thanks for PR! which of the two files is the game?

2023-02-18 06:37 UTC, Arpan-206 commented on games/UNTITLED (1).js
> +const player = "p";
Author and title comment is missing.

2023-02-18 06:41 UTC, Arpan-206 requested changes

2023-02-18 06:41 UTC, Arpan-206 commented on games/UNTITLED (1).js
> +const player = "p";
Author and title comment is missing.

2023-02-18 06:42 UTC, Arpan-206 commented
In the file `games/UNTITLED (1).js` maybe try adding a score or timer?

2023-03-15 01:13 UTC, grymmy commented
@Mani-kanta-0539 I am closing this PR.  **You are free to reopen this PR yourself** (or reach out to me directly!) and continue advocating for this code landing, but it seems that it hasn't been acted upon for 3 months.

2023-03-15 01:13 UTC, closed without merging