puzzle_simple_5
hackclub/sprig pull request #693
Opened 2022-12-31 20:36 UTC by P-Rama-Ganesh

# Your checklist for this pull request

## About your game

What is your game about? 
Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

How to play your game?
<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/121034092/210155166-822797da-318c-454a-aa36-f48e7e0bd8d4.PNG">
ou keyboard to restart the level
 Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

2022-12-31 22:16 UTC, LucasHT22 commented
Thanks for PR! How about adding a little more to your Dodging game? Is the name My_First_Game really the name? if you need help, call me :)

2022-12-31 22:21 UTC, P-Rama-Ganesh commented
I actually kept my game  as puzzle_simple_5

On Sun, 1 Jan 2023 at 03:46, Lucas ***@***.***> wrote:

> Thanks for PR! How about adding a little more to your Dodging game? Is the
> name My_First_Game really the name? if you need help, call me :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/sprig/pull/693#issuecomment-1368286750>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A43NK3BVDQA5SZH56KV6DTLWQCWC7ANCNFSM6AAAAAATNWYHTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-01 23:36 UTC, LucasHT22 commented
I can't solve the last 2 levels, could you show me how to solve it?

2023-01-02 03:18 UTC, SamDev-7 commented
You're uploading four games, are you sure you want to do that?
Also, `puzzle_simple_five.js` isn't in the games directory, it needs to be moved. 
The test is also failing, try to fix it and let us know if you need any help!
Happy hacking!

2023-01-02 10:37 UTC, P-Rama-Ganesh commented
yes i need help

2023-01-19 13:19 UTC, leomcelroy commented
@P-Rama-Ganesh were you able to get the help you needed! There are lots of people active in the #sprig channel on the [Hack Club Slack](https://hackclub.com/slack/) if you need more.

2023-01-20 13:54 UTC, SamDev-7 requested changes
Just to confirm, you want to submit `puzzle_simple_5.js`. If so, can you remove the other games?
Please move `puzzle_simple_5.js` to the `games/` directory. This can be done by renaming the file to `games/puzzle_simple_5.js`.
Please also rename the image to `puzzle_simple_5.png`.

You're so close to getting a sprig!

2023-01-20 13:54 UTC, SamDev-7 commented on puzzle_simple_5.js
> +
```suggestion
*/

```
You forgot to close the comment!

2023-03-15 01:14 UTC, grymmy commented
@P-Rama-Ganesh I am closing this PR.  **You are free to reopen this PR yourself** (or reach out to me directly!) and continue advocating for this code landing, but it seems that it hasn't been acted upon for 3 months.

2023-03-15 01:14 UTC, closed without merging