Maze Runner (Can't fill out form, big white box is blocking it, please help!)
hackclub/sprig pull request #969
Opened 2023-03-14 19:03 UTC by charlienicholson3

#                                                   Your checklist for this pull request

## Author                 name

**Author:**

##              About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

2023-03-14 19:07 UTC, LucasHT22 requested changes
Hey! Thanks for PR!

What is your game about?

How do you play your game?

2023-03-18 11:53 UTC, charlienicholson3 commented
I'm pretty sure I made those changes BTW.

2023-03-18 14:09 UTC, LucasHT22 commented
Sorry for the delay! I'll check

2023-03-18 15:47 UTC, charlienicholson3 commented
Is there a way to change the name of the file (Maze Runner) to maze-runner without re-uploading it? I think that might be a problem.

2023-03-19 00:13 UTC, LucasHT22 commented
no problems with the name, but it would be nice if you changed it, we have 2 games with that name

2023-03-19 12:16 UTC, charlienicholson3 commented
Is it good for publishing now?

2023-03-19 23:36 UTC, LucasHT22 approved these changes
Ok, good game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

2023-03-19 23:37 UTC, merged